import React,{useEffect,useMemo,useState} from 'react';
import {CASE_001,CaseDocument,CasePerson} from '../../data/case001';

type Tab='desk'|'case'|'documents'|'people'|'evidence'|'timeline'|'requests'|'reports'|'notes'|'conclusion';
type Req={id:number;subject:string;question:string;status:'pending'|'complete';readyAt:number;result?:string};
const KEY='blackwood_case001_v5'; const DAY=60_000;
const css:React.CSSProperties={fontFamily:'Georgia,serif',color:'#241f19'};
const btn:React.CSSProperties={border:'1px solid #b9a98f',background:'#f4eddf',padding:'11px 14px',cursor:'pointer',textAlign:'left'};

export const DetectiveGame:React.FC=()=>{
 const [tab,setTab]=useState<Tab>('desk'); const [opened,setOpened]=useState<string[]>([]); const [notes,setNotes]=useState(''); const [requests,setRequests]=useState<Req[]>([]); const [selected,setSelected]=useState<CaseDocument|null>(null); const [person,setPerson]=useState<CasePerson|null>(null); const [now,setNow]=useState(Date.now()); const [intro,setIntro]=useState(true); const [sent,setSent]=useState(false); const [newspaper,setNewspaper]=useState(false); const [theory,setTheory]=useState(''); const [selectedEvidence,setSelectedEvidence]=useState<string[]>([]);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s){setTab(s.tab||'desk');setOpened(s.opened||[]);setNotes(s.notes||'');setRequests(s.requests||[]);setTheory(s.theory||'');setSelectedEvidence(s.selectedEvidence||[]);setIntro(false)}}catch{}},[]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({tab,opened,notes,requests,theory,selectedEvidence}))},[tab,opened,notes,requests,theory,selectedEvidence]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{setRequests(v=>v.map(r=>r.status==='pending'&&r.readyAt<=Date.now()?{...r,status:'complete',result:reportFor(r.subject,r.question)}:r))},[now]);
 const docs=CASE_001.documents; const completed=requests.filter(r=>r.status==='complete'); const pending=requests.filter(r=>r.status==='pending');
 const openDoc=(d:CaseDocument)=>{setOpened(v=>v.includes(d.id)?v:[...v,d.id]);setSelected(d)};
 const visibleDocs=docs.filter(d=>d.id==='police'||d.id==='kitchen'||d.id==='note'||opened.includes(d.id));
 const unlocked=useMemo(()=>({home:opened.length>0,vehicle:opened.some(x=>['helen','street'].includes(x)),archive:opened.some(x=>['school','daniel','archive'].includes(x)),photo:opened.some(x=>['note','photo'].includes(x)),clock:opened.includes('note')}),[opened]);
 const requestOptions=[
  ['Apartment / scene','Look for details the original police examination may have overlooked.','scene'],
  ...(unlocked.clock?[['Wall clock','Establish whether the 20:59 display can be trusted.','clock'] as const]:[]),
  ...(unlocked.vehicle?[['Vehicle / EW-19','Check the history and ownership of the blue sedan.','vehicle'] as const]:[]),
  ...(unlocked.archive?[['1998 archive','Examine the disputed attendance record and what Edward Ward reported.','archive'] as const]:[]),
  ...(unlocked.photo?[['Old photograph','Establish why the photograph was kept outside the normal staff file.','photo'] as const]:[]),
  ...(opened.includes('school')?[['Daniel Hayes','Ask what Anna discovered and what she said about the original record.','daniel'] as const]:[]),
  ...(opened.includes('helen')?[['Helen Ward','Clarify the 21:10 sound, footsteps and the blue sedan.','helen'] as const]:[])
 ];
 function send(subject:string,question:string){if(pending.length>=2)return;setRequests(v=>[{id:Date.now(),subject,question,status:'pending',readyAt:Date.now()+DAY},...v]);setTab('requests')}
 const conclusionReady=selectedEvidence.length>=3 && theory.trim().length>=80;
 const submit=()=>{if(conclusionReady)setSent(true)};
 if(sent&&!newspaper)return <Shell tab={tab} setTab={setTab} caseClosed><section style={page}><div style={eyebrow}>CASE 001 · REPORT SUBMITTED</div><h1 style={h1}>The case is in the police’s hands.</h1><p style={lead}>Your conclusion and selected supporting evidence have been sent to North District Police. Blackwood’s work on CASE-001 is complete.</p><button style={button} onClick={()=>setNewspaper(true)}>Close file</button></section></Shell>;
 if(newspaper)return <Shell tab={tab} setTab={setTab} caseClosed><section style={page}><div style={eyebrow}>SEVEN DAYS LATER · THE EVENING REGISTER</div><article style={{background:'#eee5d4',border:'1px solid #b9a98f',padding:30}}><h1 style={h1}>MISSING TEACHER CASE REOPENED</h1><p style={lead}>Police have arrested a former St. Alden school administrator following new evidence concerning Anna Bell’s disappearance and a disputed 1998 school record.</p><p>Investigators confirmed that the original voluntary-absence classification was abandoned. Evidence submitted by Blackwood Detective Agency helped establish that the initial timeline could not be trusted.</p><p><strong>A suspect has been arrested and is being held pending further questioning.</strong></p></article><div style={{marginTop:28,borderTop:'1px solid #b9a98f',paddingTop:20}}><div style={eyebrow}>NEXT FILE</div><h2>CASE-002</h2><p>A separate case has arrived at Blackwood.</p><button style={button} onClick={()=>alert('CASE-002 will be added as the next independent case.')}>Open incoming file</button></div></section></Shell>;
 return <Shell tab={tab} setTab={setTab}><div style={layout}><aside style={sidebar}><div style={eyebrow}>BLACKWOOD</div><h2 style={{margin:'8px 0'}}>Detective Agency</h2><div style={small}>PRIVATE INVESTIGATIONS</div><hr/><div style={eyebrow}>ACTIVE CASE</div><strong>CASE-001</strong><div style={small}>THE EMPTY ROOM</div><nav style={{display:'grid',gap:6,marginTop:22}}>{(['desk','case','documents','people','evidence','timeline','requests','reports','notes','conclusion'] as Tab[]).map(x=><button key={x} style={{...btn,background:tab===x?'#ded1ba':'#f4eddf'}} onClick={()=>setTab(x)}>{label(x)}</button>)}</nav><div style={{marginTop:'auto',fontSize:12,opacity:.65}}>You investigate. Arthur travels.</div></aside><main style={main}>
 {tab==='desk'&&<Desk opened={opened} pending={pending} reports={completed} onOpen={openDoc} setTab={setTab}/>} 
 {tab==='case'&&<CasePanel openDoc={openDoc}/>} {tab==='documents'&&<Documents docs={visibleDocs} opened={opened} openDoc={openDoc}/>} {tab==='people'&&<People onOpen={setPerson}/>} {tab==='evidence'&&<Evidence selected={selectedEvidence} setSelected={setSelectedEvidence} opened={opened}/>} {tab==='timeline'&&<Timeline opened={opened}/>} {tab==='requests'&&<Requests options={requestOptions} pending={pending} completed={completed} send={send} now={now}/>} {tab==='reports'&&<Reports reports={completed}/>} {tab==='notes'&&<section style={page}><div style={eyebrow}>PRIVATE NOTEBOOK</div><h1 style={h1}>What do you think happened?</h1><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Write observations, contradictions and theories. The game will not tell you what to think." style={{width:'100%',minHeight:380,padding:18,background:'#f8f1e3',border:'1px solid #b9a98f',fontFamily:'Georgia,serif',fontSize:16}}/></section>} {tab==='conclusion'&&<Conclusion theory={theory} setTheory={setTheory} selected={selectedEvidence} setSelected={setSelectedEvidence} submit={submit} ready={conclusionReady}/>} 
 </main></div>{selected&&<Modal title={selected.title} close={()=>setSelected(null)}><p style={meta}>{selected.date} · {selected.source}</p><pre style={pre}>{selected.content}</pre></Modal>}{person&&<Modal title={person.name} close={()=>setPerson(null)}><p style={meta}>{person.role}</p><p style={lead}>{person.note}</p></Modal>}{intro&&<Intro close={()=>setIntro(false)}/>}</Shell>
};

const label=(x:Tab)=>({desk:'Desk',case:'Case file',documents:'Documents',people:'People',evidence:'Evidence board',timeline:'Timeline',requests:'Field requests',reports:'Field reports',notes:'Notebook',conclusion:'Final deduction'}[x]);
const page:React.CSSProperties={maxWidth:900,margin:'0 auto',padding:'42px 30px'}; const h1:React.CSSProperties={fontSize:'clamp(34px,5vw,58px)',fontWeight:500,margin:'8px 0 20px'}; const lead:React.CSSProperties={fontSize:18,lineHeight:1.7}; const small:React.CSSProperties={fontSize:12,opacity:.65}; const eyebrow:React.CSSProperties={fontSize:11,letterSpacing:2.5,fontWeight:700,opacity:.6}; const meta:React.CSSProperties={fontSize:12,opacity:.6}; const pre:React.CSSProperties={whiteSpace:'pre-wrap',fontFamily:'Georgia,serif',fontSize:16,lineHeight:1.8}; const button:React.CSSProperties={...btn,textAlign:'center',background:'#2d2821',color:'#f5eddf',borderColor:'#2d2821'}; const layout:React.CSSProperties={display:'grid',gridTemplateColumns:'245px 1fr',minHeight:'100vh'}; const sidebar:React.CSSProperties={background:'#302a22',color:'#eee5d4',padding:24,display:'flex',flexDirection:'column'}; const main:React.CSSProperties={background:'#eee5d4',minWidth:0};
const Shell:React.FC<{tab:Tab;setTab:(t:Tab)=>void;children:React.ReactNode;caseClosed?:boolean}>=({children})=><div style={{...css,minHeight:'100vh',background:'#eee5d4'}}><header style={{height:62,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 25px',borderBottom:'1px solid #b9a98f',background:'#f5eddf'}}><strong>BLACKWOOD</strong><span style={small}>{'CASE-001 · THE EMPTY ROOM'}</span><span style={small}>{new Date().toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short',year:'numeric'})}</span></header>{children}</div>;

const Desk:React.FC<any>=({opened,pending,reports,setTab})=><section style={page}><div style={eyebrow}>BLACKWOOD DETECTIVE AGENCY</div><h1 style={h1}>The Empty Room</h1><p style={lead}>A case the police closed before the important questions were answered.</p><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12,marginTop:30}}>{[['DOCUMENTS',opened.length],['IN THE FIELD',pending.length],['REPORTS',reports.length]].map(([a,b])=><div key={String(a)} style={{border:'1px solid #b9a98f',padding:18}}><div style={eyebrow}>{a}</div><strong style={{fontSize:28}}>{b}</strong></div>)}</div><div style={{marginTop:38,borderTop:'1px solid #b9a98f',paddingTop:25}}><div style={eyebrow}>UNRESOLVED QUESTIONS</div><ul style={{lineHeight:2,fontSize:17}}><li>Why did police classify the disappearance as voluntary?</li><li>What happened between 18:12 and the door sound?</li><li>Why did Anna tell Margaret to find the old photograph?</li><li>What was wrong with the 1998 record?</li><li>Who was connected to the blue sedan?</li></ul><button style={button} onClick={()=>setTab('case')}>Open case file</button></div></section>;
const CasePanel:React.FC<{openDoc:(d:CaseDocument)=>void}>=({openDoc})=><section style={page}><div style={eyebrow}>CASE FILE · CLIENT LETTER</div><h1 style={h1}>Margaret Bell</h1><pre style={pre}>{CASE_001.openingLetter}</pre><div style={{marginTop:35}}><div style={eyebrow}>POLICE POSITION</div><p style={lead}>{CASE_001.premise}</p><button style={button} onClick={()=>openDoc(CASE_001.documents[0])}>Read police report</button></div></section>;
const Documents:React.FC<{docs:CaseDocument[];opened:string[];openDoc:(d:CaseDocument)=>void}>=({docs,opened,openDoc})=><section style={page}><div style={eyebrow}>DOCUMENTS</div><h1 style={h1}>The file</h1><div style={{display:'grid',gap:10}}>{docs.map(d=><button key={d.id} style={{...btn,background:opened.includes(d.id)?'#e1d4bd':'#f4eddf'}} onClick={()=>openDoc(d)}><strong>{d.title}</strong><div style={small}>{d.date} · {d.source}</div></button>)}</div></section>;
const People:React.FC<{onOpen:(p:CasePerson)=>void}>=({onOpen})=><section style={page}><div style={eyebrow}>PEOPLE</div><h1 style={h1}>People in the case</h1><div style={{display:'grid',gap:10}}>{CASE_001.people.map(p=><button key={p.id} style={btn} onClick={()=>onOpen(p)}><strong>{p.name}</strong><div style={small}>{p.role}</div></button>)}</div></section>;
const Evidence:React.FC<{selected:string[];setSelected:(x:string[])=>void;opened:string[]}>=({selected,setSelected,opened})=><section style={page}><div style={eyebrow}>EVIDENCE BOARD</div><h1 style={h1}>What can you prove?</h1><p style={lead}>Select evidence you would be willing to put into the police report. Nothing here declares a suspect guilty.</p><div style={{display:'grid',gap:10}}>{CASE_001.evidence.filter(e=>opened.length>0||e.id==='ev-clock').map(e=>{const on=selected.includes(e.id);return <button key={e.id} style={{...btn,background:on?'#d9ccb3':'#f4eddf'}} onClick={()=>setSelected(on?selected.filter(x=>x!==e.id):[...selected,e.id])}><strong>{on?'✓ ':''}{e.title}</strong><div style={small}>{e.source} · {e.strength.toUpperCase()}</div><p style={{marginBottom:0}}>{e.description}</p></button>})}</div></section>;
const Timeline:React.FC<{opened:string[]}>=({opened})=><section style={page}><div style={eyebrow}>TIMELINE</div><h1 style={h1}>What actually fits?</h1><p style={lead}>Events are labelled by certainty. A reported time is not automatically a confirmed time.</p><div style={{borderLeft:'2px solid #8e8069',paddingLeft:25}}>{CASE_001.timeline.map(e=><article key={e.id} style={{marginBottom:25}}><strong style={{fontSize:22}}>{e.time}</strong><div><strong>{e.title}</strong> <span style={small}>· {e.certainty}</span></div><p>{e.description}</p></article>)}</div></section>;
const Requests:React.FC<any>=({options,pending,completed,send,now})=><section style={page}><div style={eyebrow}>FIELD REQUESTS · ARTHUR VALE</div><h1 style={h1}>Ask a question.</h1><p style={lead}>Arthur investigates questions you choose. He does not hand you a predefined quest chain.</p>{pending.length>0&&<div style={{marginBottom:20,border:'1px solid #b9a98f',padding:15}}>Arthur is in the field: {pending.map((r:Req)=><div key={r.id}>{r.subject} · {Math.max(0,Math.ceil((r.readyAt-now)/1000))}s remaining</div>)}</div>}<div style={{display:'grid',gap:10}}>{options.filter((x:any)=>!completed.some((r:Req)=>r.subject===x[0])).map((x:any)=><button key={x[0]} disabled={pending.length>=2} style={{...btn,opacity:pending.length>=2?.5:1}} onClick={()=>send(x[0],x[1])}><strong>{x[0]}</strong><div>{x[1]}</div></button>)}</div></section>;
const Reports:React.FC<{reports:Req[]}>=({reports})=><section style={page}><div style={eyebrow}>FIELD REPORTS</div><h1 style={h1}>Arthur’s findings</h1>{reports.length===0?<p style={lead}>No field reports yet.</p>:reports.map(r=><article key={r.id} style={{border:'1px solid #b9a98f',padding:20,marginBottom:12}}><strong>{r.subject}</strong><p>{r.result}</p></article>)}</section>;
const Conclusion:React.FC<any>=({theory,setTheory,selected,setSelected,submit,ready})=><section style={page}><div style={eyebrow}>FINAL DEDUCTION</div><h1 style={h1}>Make your case.</h1><p style={lead}>The police do not need a guess. They need a defensible reconstruction. Explain what happened, why the original classification fails, and how your evidence supports the conclusion.</p><textarea value={theory} onChange={e=>setTheory(e.target.value)} placeholder="Write your conclusion in your own words…" style={{width:'100%',minHeight:240,padding:18,background:'#f8f1e3',border:'1px solid #b9a98f',fontFamily:'Georgia,serif',fontSize:16,lineHeight:1.6}}/><h3>Supporting evidence · {selected.length}</h3><div style={{display:'grid',gap:8}}>{CASE_001.evidence.map(e=>{const on=selected.includes(e.id);return <button key={e.id} style={{...btn,background:on?'#d9ccb3':'#f4eddf'}} onClick={()=>setSelected(on?selected.filter((x:string)=>x!==e.id):[...selected,e.id])}>{on?'✓ ':''}{e.title}</button>})}</div><p style={small}>At least 80 characters and 3 evidence items are required.</p><button disabled={!ready} style={{...button,opacity:ready?1:.4,marginTop:15}} onClick={submit}>Send evidence to police</button></section>;
const Modal:React.FC<{title:string;close:()=>void;children:React.ReactNode}>=({title,close,children})=><div style={{position:'fixed',inset:0,background:'rgba(20,17,13,.62)',display:'grid',placeItems:'center',padding:20,zIndex:20}}><article style={{maxWidth:760,width:'100%',maxHeight:'85vh',overflow:'auto',background:'#eee5d4',padding:32,border:'1px solid #b9a98f'}}><button style={{float:'right',...btn}} onClick={close}>Close</button><h2 style={{fontSize:32,fontWeight:500}}>{title}</h2>{children}</article></div>;
const Intro:React.FC<{close:()=>void}>=({close})=><div style={{position:'fixed',inset:0,background:'rgba(20,17,13,.72)',display:'grid',placeItems:'center',padding:20,zIndex:30}}><article style={{maxWidth:700,background:'#eee5d4',padding:40,border:'1px solid #b9a98f'}}><div style={eyebrow}>BLACKWOOD DETECTIVE AGENCY</div><h1 style={h1}>A case the police couldn't close.</h1><p style={lead}>A private client has brought you a missing-person case. The police already have a theory. Your job is not to follow missions. Read the evidence, ask questions, find contradictions, build a timeline and send the police a conclusion you can defend.</p><p><strong>There is no single “next task”.</strong> If something interests you, investigate it.</p><button style={button} onClick={close}>Accept CASE-001</button></article></div>;
function reportFor(subject:string,question:string){const map:Record<string,string>={
 'Apartment / scene':'The apartment remains orderly. The front door shows no visible forced entry. Anna’s coat, handbag and glasses are still inside. The scene cannot establish who closed the door.',
 'Wall clock':'The kitchen clock is battery powered and stopped at 20:59 with a nearly depleted battery. There is no reliable way to prove when it stopped. It should not be used to establish the time of the door sound.',
 'Vehicle / EW-19':'A shop photograph shows a dark blue sedan before the rain, with partial registration EW-19. Historical records connect EW-19 to a vehicle assigned to Edward Ward from 1998–2001, but the current owner and driver cannot be established.',
 '1998 archive':'The 1998 ledger contains a PRESENT/ABSENT contradiction. Edward Ward appears in the maintenance section, but a personnel note shows he reported an irregularity to administration. Several pages are missing.',
 'Old photograph':'The 1998 staff photograph was hidden inside the damaged attendance ledger. The rear-entrance figure can be identified as Edward Ward from the staff roster, but the blue mark and the instruction not to file it under staff do not prove why it was hidden.',
 'Daniel Hayes':'Daniel confirms Anna was investigating the 1998 archive. He remembers an old story about an argument near the rear entrance and says Anna believed someone had deliberately kept the original record out of sight.',
 'Helen Ward':'Helen confirms she heard the door but never saw who used it. She heard heavy footsteps afterward. She saw the blue sedan earlier, but cannot identify its driver. She also confirms Edward Ward is her brother.'};return map[subject]||`Arthur investigated: ${question}`}
