import { DirectoryContact } from '../../types/mail';

export const NPD_DIRECTORY: DirectoryContact[] = [
  {
    id: 'DIR-001',
    officerId: 'OFF-2018',
    name: 'Captain Laura Bennett',
    rank: 'Captain',
    badgeNumber: '2018',
    department: 'Records & Archive Division',
    division: 'Archive Administration & Public Records',
    role: 'Records Division Commander',
    email: 'lbennett@records.npd.local',
    phoneExt: 'x3401',
    directPhone: '(555) 382-3401',
    officeLocation: 'Room 204, Records Annex, 800 High Street',
    status: 'ACTIVE',
    supervisor: 'Deputy Chief of Police',
    employmentPeriod: '2001-Present',
    deskAssignment: 'Office 204-A',
    clearanceLevel: 'LEVEL 4 - RESTRICTED',
    notes: 'Supervisory officer managing the 2026 digital audit and reconciliation of archived cold case dockets.'
  },
  {
    id: 'DIR-002',
    officerId: 'OFF-3014',
    personId: 'P-003014',
    name: 'Daniel Hayes',
    rank: 'Detective (Former)',
    badgeNumber: '3014',
    department: 'Major Crimes Division (1998)',
    division: 'Squad 3 - Missing Persons Unit',
    role: 'Lead Forensic Detective on CASE-1998-027',
    email: 'dhayes@investigations.npd.local',
    phoneExt: 'x2844',
    directPhone: '(555) 382-2844',
    officeLocation: 'Former Desk 03, Squad 3 Bullpen (Transferred 2008)',
    status: 'TRANSFERRED',
    supervisor: 'Captain Arthur Vance (1998)',
    employmentPeriod: '1992-2008 (Transferred to County SID)',
    deskAssignment: 'Archives Retained File Bay 4',
    clearanceLevel: 'LEVEL 3',
    notes: 'Author of primary investigative reports R-1998-112 and R-1998-114 regarding the disappearance of Anna Bell.'
  },
  {
    id: 'DIR-003',
    officerId: 'OFF-4081',
    name: 'Sarah Miller',
    rank: 'Detective',
    badgeNumber: '4081',
    department: 'Cold Case & Special Review Unit',
    division: 'Detective Bureau',
    role: 'Lead Workstation Operator / Case 27 Auditor',
    email: 'investigator@workstation-07.npd.local',
    phoneExt: 'x4081',
    directPhone: '(555) 382-4081',
    officeLocation: 'Workstation 07, Detective Bullpen, 4th Precinct',
    status: 'ACTIVE',
    supervisor: 'Lieutenant Marcus Reed',
    employmentPeriod: '2018-Present',
    deskAssignment: 'Workstation WS-07',
    clearanceLevel: 'LEVEL 4 - RESTRICTED',
    notes: 'Current session investigator tasked with systematic re-evaluation of Case 27 records and discrepancies.'
  },
  {
    id: 'DIR-004',
    officerId: 'OFF-1012',
    name: 'Arthur Vance',
    rank: 'Captain',
    badgeNumber: '1012',
    department: 'Detective Bureau / Archive Oversight',
    division: 'Executive Command',
    role: 'Supervising Detective Commander',
    email: 'avance@command.npd.local',
    phoneExt: 'x1012',
    directPhone: '(555) 382-1012',
    officeLocation: 'Room 410, Police Headquarters, Civic Center',
    status: 'ACTIVE',
    supervisor: 'Chief of Police',
    employmentPeriod: '1984-Present',
    deskAssignment: 'Executive Suite 410',
    clearanceLevel: 'EXECUTIVE',
    notes: 'Supervised Case 27 closure in 1999. Presided over the 2004 archive reorganization under security override SEC-VANCE-89.'
  },
  {
    id: 'DIR-005',
    officerId: 'OFF-5109',
    name: 'Marcus Thorne',
    rank: 'Senior Records Specialist',
    badgeNumber: '5109',
    department: 'Records & Archive Division',
    division: 'Cold Storage & Microfilm Vault',
    role: 'Archive Vault Custodian',
    email: 'mthorne@records.npd.local',
    phoneExt: 'x3415',
    directPhone: '(555) 382-3415',
    officeLocation: 'Basement Vault B-12, County Archive Facility, 800 High St',
    status: 'ACTIVE',
    supervisor: 'Captain Laura Bennett',
    employmentPeriod: '2011-Present',
    deskAssignment: 'Vault Desk B-12',
    clearanceLevel: 'LEVEL 3',
    notes: 'Handles legacy physical docket retrievals, microfilm scans, and document preservation requests.'
  },
  {
    id: 'DIR-006',
    officerId: 'OFF-5820',
    name: 'Dr. Elena Rostova',
    rank: 'Lead Forensic Analyst',
    badgeNumber: '5820',
    department: 'Forensic Sciences Division',
    division: 'Trace & Biological Evidence Laboratory',
    role: 'Senior Forensic Scientist',
    email: 'erostova@forensics.npd.local',
    phoneExt: 'x5820',
    directPhone: '(555) 382-5820',
    officeLocation: 'Forensic Lab Bay 2, 820 High Street Annex',
    status: 'ACTIVE',
    supervisor: 'Director of Crime Laboratory',
    employmentPeriod: '2014-Present',
    deskAssignment: 'Forensic Lab Console 2',
    clearanceLevel: 'LEVEL 4 - RESTRICTED',
    notes: 'Performs spectrographic analysis, DNA comparative assays, and trace custody verifications for active and cold files.'
  },
  {
    id: 'DIR-007',
    officerId: 'OFF-3310',
    name: 'Marcus Reed',
    rank: 'Lieutenant',
    badgeNumber: '3310',
    department: 'Cold Case & Special Review Unit',
    division: 'Detective Bureau',
    role: 'Cold Case Review Supervisor',
    email: 'mreed@investigations.npd.local',
    phoneExt: 'x2210',
    directPhone: '(555) 382-2210',
    officeLocation: 'Room 308, 4th Precinct Detective Bureau',
    status: 'ACTIVE',
    supervisor: 'Captain of Detectives',
    employmentPeriod: '2005-Present',
    deskAssignment: 'Office 308-B',
    clearanceLevel: 'LEVEL 4 - RESTRICTED',
    notes: 'Author of Cold Case Audit Directive and supervisory officer for Workstation 07 assignments.'
  },
  {
    id: 'DIR-008',
    officerId: 'OFF-2241',
    name: 'Karen Kowalski',
    rank: 'Senior Dispatch Supervisor',
    badgeNumber: '2241',
    department: 'Communications & 911 CAD Operations',
    division: 'Emergency Services Dispatch',
    role: 'CAD Archive Specialist',
    email: 'kkowalski@dispatch.npd.local',
    phoneExt: 'x9110',
    directPhone: '(555) 382-9110',
    officeLocation: 'CAD Console 4, Municipal Communications Center',
    status: 'ACTIVE',
    supervisor: 'Director of Emergency Communications',
    employmentPeriod: '1996-Present',
    deskAssignment: 'Console CAD-04',
    clearanceLevel: 'LEVEL 2',
    notes: 'Experienced dispatcher with direct familiarity with historical CAD call logging during September 1998.'
  },
  {
    id: 'DIR-009',
    officerId: 'OFF-4902',
    name: 'Walter Briggs',
    rank: 'Evidence Custody Specialist',
    badgeNumber: '4902',
    department: 'Property & Evidence Vault',
    division: 'Evidence Control Division',
    role: 'Head Property Clerk',
    email: 'wbriggs@evidence.npd.local',
    phoneExt: 'x4902',
    directPhone: '(555) 382-4902',
    officeLocation: 'Secure Evidence Receiving Bay, Precinct 4 Basement',
    status: 'ACTIVE',
    supervisor: 'Lieutenant of Administration',
    employmentPeriod: '2000-Present',
    deskAssignment: 'Evidence Vault Intake Desk',
    clearanceLevel: 'LEVEL 3',
    notes: 'Custodian of physical lockers for CASE-1998-027, maintaining intake ledgers and chain of custody tracking.'
  },
  {
    id: 'DIR-010',
    officerId: 'OFF-1044',
    name: 'John Mercer',
    rank: 'Detective (Retired)',
    badgeNumber: '1044',
    department: 'Burglary & Special Investigations',
    division: 'Historic Squad (Retired 2001)',
    role: 'Former Primary Detective on CASE-1987-014',
    email: 'jmercer@alumni.npd.local',
    phoneExt: 'N/A (Retired)',
    directPhone: '(555) 481-9920',
    officeLocation: 'Retired - Inactive Archive Record',
    status: 'RETIRED',
    supervisor: 'Captain E. Holloway (Historical)',
    employmentPeriod: '1974-2001 (Honorably Retired)',
    deskAssignment: 'N/A',
    clearanceLevel: 'LEVEL 1',
    notes: 'Investigated the 1987 Crownline freight theft. Filed investigative report R-1987-042.'
  }
];
