import React, { useEffect, useMemo, useState } from 'react';
import { CASE_001, CaseDocument, CasePerson, Evidence } from '../../data/case001';

type Tab='desk'|'case'|'documents'|'people'|'evidence'|'timeline'|'requests'|'reports'|'notes'|'deductions'|'conclusion';
type Request={id:string;subject:string;question:string;documentId:string;readyAt:number;complete:boolean};
type Conclusion={what:string;who:string[];when:string;why:string;proof:string[]};
type Deduction={id:string;title:string;evidenceIds:string[];theory:string;status:'untested'|'supported'|'weakened'};
const SAVE='blackwood_case001_v10';
const FIELD_TIME=45000;
const labels:Record<Tab,string>={desk:'Desk',case:'Case file',documents:'Documents',people:'People',evidence:'Evidence board',timeline:'Timeline',requests:'Arthur / fieldwork',reports:'Field reports',notes:'Notebook',deductions:'Case theories',conclusion:'Final deduction'};
const emptyConclusion:Conclusion={what:'',who:[],when:'',why:'',proof:[]};

export const DetectiveGame:React.FC=()=>{
 const [tab,setTab]=useState<Tab>('desk');
 const [opened,setOpened]=useState<string[]>([]); const [notes,setNotes]=useState(''); const [requests,setRequests]=useState<Request[]>([]);
 const [selectedEvidence,setSelectedEvidence]=useState<string[]>([]); const [deductions,setDeductions]=useState<Deduction[]>([]); const [deductionText,setDeductionText]=useState('');
 const [conclusion,setConclusion]=useState<Conclusion>(emptyConclusion); const [modalDoc,setModalDoc]=useState<CaseDocument|null>(null); const [modalPerson,setModalPerson]=useState<CasePerson|null>(null);
 const [intro,setIntro]=useState(true); const [submitted,setSubmitted]=useState(false); const [newspaper,setNewspaper]=useState(false); const [now,setNow]=useState(Date.now());
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(SAVE)||'null');if(!s)return;setTab(s.tab||'desk');setOpened(Array.isArray(s.opened)?s.opened:[]);setNotes(s.notes||'');setRequests(Array.isArray(s.requests)?s.requests:[]);setSelectedEvidence(Array.isArray(s.selectedEvidence)?s.selectedEvidence:[]);setDeductions(Array.isArray(s.deductions)?s.deductions:[]);setConclusion({...emptyConclusion,...(s.conclusion||{}),who:Array.isArray(s.conclusion?.who)?s.conclusion.who:[],proof:Array.isArray(s.conclusion?.proof)?s.conclusion.proof:[]});setSubmitted(Boolean(s.submitted));setNewspaper(Boolean(s.newspaper));setIntro(false)}catch{}} ,[]);
 useEffect(()=>{localStorage.setItem(SAVE,JSON.stringify({tab,opened,notes,requests,selectedEvidence,deductions,conclusion,submitted,newspaper}))},[tab,opened,notes,requests,selectedEvidence,deductions,conclusion,submitted,newspaper]);
 useEffect(()=>{const t=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(t)},[]);
 useEffect(()=>{setRequests(c=>c.map(r=>r.complete||r.readyAt>now?r:{...r,complete:true}))},[now]);
 const completed=requests.filter(r=>r.complete),pending=requests.filter(r=>!r.complete),openedSet=useMemo(()=>new Set(opened),[opened]);
 const openDocument=(doc:CaseDocument)=>{setOpened(c=>c.includes(doc.id)?c:[...c,doc.id]);setModalDoc(doc)};
 const openPerson=(p:CasePerson)=>{setOpened(c=>c.includes(p.id)?c:[...c,p.id]);setModalPerson(p)};
 const requestOptions=useMemo(()=>{
  const o:Array<{id:string;subject:string;question:string;documentId:string}>=[];
  if(openedSet.has('police')||openedSet.has('note')){o.push({id:'clock',subject:'Inspect the apartment clock',question:'Establish whether 20:59 is a real event or a misleading trace.',documentId:'clock'});o.push({id:'weather',subject:'Reconstruct the rain window',question:'Use weather data as an independent time anchor.',documentId:'weather'});o.push({id:'market',subject:'Trace the 20:31 card purchase',question:'Find where the card was used and what the transaction can actually prove.',documentId:'market'});}
  if(openedSet.has('police')||openedSet.has('helen')){o.push({id:'helen2',subject:'Interview Helen Ward',question:'Resolve the door sound, footsteps and the blue sedan without assuming who drove it.',documentId:'helen2'});o.push({id:'street',subject:'Check the street camera',question:'Identify the vehicle, direction and weather conditions around the building.',documentId:'street'});}
  if(openedSet.has('market')||openedSet.has('street'))o.push({id:'vehicle',subject:'Trace EW-19 through vehicle records',question:'Determine whether the plate identifies a current owner or only an old vehicle association.',documentId:'vehicle'});
  if(openedSet.has('school')||openedSet.has('note')||openedSet.has('police'))o.push({id:'archive',subject:'Open the 1998 archive',question:'Compare the original attendance record with the later correction and missing pages.',documentId:'archive'});
  if(openedSet.has('archive')){o.push({id:'maintenance',subject:'Inspect the 1998 maintenance log',question:'Find out what happened at the rear entrance on the disputed date.',documentId:'maintenance'});o.push({id:'photo-context',subject:'Examine the hidden photograph',question:'Determine why a staff photograph was separated from the official file.',documentId:'photo-context'});o.push({id:'edward',subject:'Interview Edward Ward',question:'Ask what he reported in 1998 and why his report disappeared from the public file.',documentId:'edward'});}
  if(openedSet.has('photo-context')||openedSet.has('archive'))o.push({id:'daniel',subject:'Interview Daniel Hayes',question:'Establish what Anna discovered before she disappeared and who knew she was looking.',documentId:'daniel'});
  if(openedSet.has('daniel')||openedSet.has('edward')){o.push({id:'vale',subject:'Interview Martin Vale',question:'Test the police timeline, his decision to close the case and his connection to St. Alden.',documentId:'vale'});o.push({id:'records',subject:'Request the sealed personnel index',question:'Follow the names that connect the 1998 incident to the present investigation.',documentId:'records'});}
  if(openedSet.has('vale')||openedSet.has('records')){o.push({id:'warehouse',subject:'Search the old archive warehouse',question:'Find the missing original pages and determine who accessed the storage room.',documentId:'warehouse'});o.push({id:'rail',subject:'Trace Anna after 20:31',question:'Check transport, station and witness records without assuming she left town.',documentId:'rail'});}
  if(openedSet.has('warehouse')||openedSet.has('rail')){o.push({id:'phone',subject:'Reconstruct Anna’s last communications',question:'Compare message times, deleted drafts and the person Anna intended to meet.',documentId:'phone'});o.push({id:'meeting',subject:'Locate the final meeting site',question:'Establish where Anna went after leaving the school investigation trail.',documentId:'meeting'});}
  return o;
 },[openedSet]);
 const sendRequest=(o:typeof requestOptions[number])=>{if(pending.length>=2||requests.some(r=>r.id===o.id))return;setRequests(c=>[...c,{...o,readyAt:Date.now()+FIELD_TIME,complete:false}])};
 const visibleDocuments=CASE_001.documents.filter(d=>['police','kitchen','note'].includes(d.id)||openedSet.has(d.id));
 const unlockedEvidence=CASE_001.evidence.filter(e=>evidenceUnlocked(e,openedSet));
 const canSubmit=selectedEvidence.length>=5&&deductions.length>=2&&conclusion.who.length>0&&['what','when','why'].every(k=>conclusion[k as 'what'|'when'|'why'].length>0)&&conclusion.proof.length>=3;
 const createDeduction=()=>{const t=deductionText.trim();if(t.length<30||selectedEvidence.length<2)return;setDeductions(c=>[...c,{id:String(Date.now()),title:`Theory ${c.length+1}`,evidenceIds:[...selectedEvidence],theory:t,status:'untested'}]);setDeductionText('')};
 if(newspaper)return <Newspaper/>; if(submitted)return <Submitted onContinue={()=>setNewspaper(true)}/>;
 return <div className="blackwood-app"><header className="blackwood-header"><div><strong>BLACKWOOD</strong><small> DETECTIVE AGENCY</small></div><div className="header-case">CASE-001 · THE EMPTY ROOM</div><div className="header-date">PRIVATE INVESTIGATION</div></header><div className="blackwood-layout"><aside className="blackwood-sidebar"><div className="sidebar-heading">ACTIVE FILE</div><h1>THE EMPTY ROOM</h1><p>CASE-001</p><div className="sidebar-rule"/><nav>{(Object.keys(labels) as Tab[]).map(x=><button key={x} className={tab===x?'nav-button active':'nav-button'} onClick={()=>setTab(x)}>{labels[x]}</button>)}</nav><div className="sidebar-footer">No quest tells you the answer.<br/>Follow the evidence until the story holds together.</div></aside><main className="blackwood-main">
 {tab==='desk'&&<Desk opened={opened} pending={pending} completed={completed} deductions={deductions} setTab={setTab}/>} {tab==='case'&&<CaseFile openDocument={openDocument}/>} {tab==='documents'&&<Documents docs={visibleDocuments} opened={openedSet} openDocument={openDocument}/>} {tab==='people'&&<People onOpen={openPerson}/>} {tab==='evidence'&&<EvidenceBoard evidence={unlockedEvidence} selected={selectedEvidence} toggle={id=>setSelectedEvidence(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/>} {tab==='timeline'&&<Timeline opened={openedSet}/>} {tab==='requests'&&<Fieldwork options={requestOptions} requests={requests} now={now} send={sendRequest} openDocument={openDocument}/>} {tab==='reports'&&<Reports requests={completed} openDocument={openDocument}/>} {tab==='notes'&&<Notebook notes={notes} setNotes={setNotes}/>} {tab==='deductions'&&<DeductionBoard evidence={unlockedEvidence} selected={selectedEvidence} setSelected={setSelectedEvidence} theory={deductionText} setTheory={setDeductionText} deductions={deductions} create={createDeduction}/>} {tab==='conclusion'&&<FinalDeduction conclusion={conclusion} setConclusion={setConclusion} selected={selectedEvidence} evidence={unlockedEvidence} deductions={deductions} submit={()=>canSubmit&&setSubmitted(true)} ready={canSubmit}/>}</main></div>{intro&&<Intro close={()=>setIntro(false)}/>} {modalDoc&&<Modal title={modalDoc.title} close={()=>setModalDoc(null)}><div className="modal-meta">{modalDoc.date} · {modalDoc.source}</div><pre>{modalDoc.content}</pre></Modal>} {modalPerson&&<Modal title={modalPerson.name} close={()=>setModalPerson(null)}><div className="modal-meta">{modalPerson.role}</div><p className="modal-copy">{modalPerson.note}</p></Modal>}</div>;
};

function evidenceUnlocked(e:Evidence,opened:Set<string>){if(e.id==='clock')return opened.has('note')||opened.has('clock');if(e.id==='card')return opened.has('market');if(e.id==='rain')return opened.has('weather');if(e.id==='car')return opened.has('street')||opened.has('vehicle');if(e.id==='archive')return opened.has('archive');if(e.id==='photo')return opened.has('photo')||opened.has('photo-context');if(e.id==='edward')return opened.has('edward')||opened.has('archive');if(e.id==='helen')return opened.has('helen2');if(e.id==='warehouse')return opened.has('warehouse');if(e.id==='phone')return opened.has('phone');if(e.id==='meeting')return opened.has('meeting');return false}
const Intro:React.FC<{close:()=>void}>=({close})=><div className="intro-overlay"><article className="intro-card"><div className="eyebrow">BLACKWOOD DETECTIVE AGENCY</div><h1>CASE-001<br/><em>The Empty Room</em></h1><p>A missing teacher. A closed police file. A trail that reaches twenty-eight years into the past.</p><p className="intro-small">There is no quest list and no highlighted culprit. Read, compare, interview, research and build the explanation yourself. Some questions will take time. Some answers will create new questions.</p><button className="dark-button" onClick={close}>Open the file</button></article></div>;
const Desk:React.FC<any>=({opened,pending,completed,deductions,setTab})=><Page><div className="eyebrow">BLACKWOOD DETECTIVE AGENCY · ACTIVE CASE</div><h2>The Empty Room</h2><p className="lede">Anna Bell has been missing for days. The first police report is only the beginning.</p><div className="stat-grid"><Stat label="FILE ITEMS" value={opened.length}/><Stat label="FIELDWORK" value={pending.length}/><Stat label="REPORTS" value={completed.length}/><Stat label="THEORIES" value={deductions.length}/></div><section className="question-panel"><div className="eyebrow">QUESTIONS WORTH FOLLOWING</div><ul><li>What happened between Anna's last confirmed sighting and the next reliable trace?</li><li>Why did a 1998 school record matter enough for Anna to investigate it days before disappearing?</li><li>Who benefits from the missing original pages?</li><li>Why do several people remember the same night differently?</li><li>Where was Anna actually going?</li></ul><button className="dark-button" onClick={()=>setTab('case')}>Begin with the client</button></section></Page>;
const CaseFile:React.FC<{openDocument:(d:CaseDocument)=>void}>=({openDocument})=><Page><div className="eyebrow">CASE FILE · CLIENT</div><h2>Margaret Bell</h2><pre className="letter">{CASE_001.openingLetter}</pre><section className="case-position"><div className="eyebrow">INITIAL POLICE POSITION</div><p>{CASE_001.premise}</p><button className="dark-button" onClick={()=>openDocument(CASE_001.documents[0])}>Read the police report</button></section></Page>;
const Documents:React.FC<any>=({docs,opened,openDocument})=><Page><div className="eyebrow">DOCUMENTS</div><h2>The file grows when you earn it.</h2><p className="lede">Documents contain facts, mistakes, omissions and competing versions.</p><div className="document-list">{docs.map((d:CaseDocument)=><button className={opened.has(d.id)?'document-card read':'document-card'} key={d.id} onClick={()=>openDocument(d)}><div className="document-type">{d.type}</div><div><strong>{d.title}</strong><small>{d.date} · {d.source}</small></div><span>OPEN</span></button>)}</div></Page>;
const People:React.FC<{onOpen:(p:CasePerson)=>void}>=({onOpen})=><Page><div className="eyebrow">PEOPLE</div><h2>Persons of interest</h2><p className="lede">A suspect is a question, not an answer. Interview records can unlock further fieldwork.</p><div className="people-grid">{CASE_001.people.map(p=><button className="person-card" key={p.id} onClick={()=>onOpen(p)}><strong>{p.name}</strong><small>{p.role}</small><span>OPEN RECORD</span></button>)}</div></Page>;
const EvidenceBoard:React.FC<{evidence:Evidence[];selected:string[];toggle:(id:string)=>void}>=({evidence,selected,toggle})=><Page><div className="eyebrow">EVIDENCE BOARD</div><h2>Evidence, not guesses</h2><p className="lede">Click a card to cite it. Selection is handled locally and does not open a new page, so the board stays stable while you build a case.</p><div className="evidence-grid">{evidence.map(e=>{const active=selected.includes(e.id);return <div key={e.id} className={active?'evidence-card selected':'evidence-card'} role="button" tabIndex={0} onClick={()=>toggle(e.id)} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' ')toggle(e.id)}}><div className="evidence-top"><strong>{e.title}</strong><span>{e.strength}</span></div><small>{e.source}</small><p>{e.description}</p><div className="evidence-select">{active?'✓ CITED':'CLICK TO CITE'}</div></div>})}</div><div className="selection-count">{selected.length} evidence item{selected.length===1?'':'s'} cited</div></Page>;
const Timeline:React.FC<{opened:Set<string>}>=({opened})=><Page><div className="eyebrow">TIMELINE</div><h2>Build the night without trusting one clock.</h2><p className="lede">Confirmed, reported and uncertain events are deliberately mixed. Later investigations can alter how you interpret earlier events.</p><div className="timeline">{CASE_001.timeline.filter(e=>e.id.startsWith('x')||e.certainty==='confirmed'||opened.has(e.id)||opened.has('weather')||opened.has('clock')).map(e=><article key={e.id}><div className="time">{e.time}</div><div><strong>{e.title}</strong><span className={`certainty ${e.certainty}`}>{e.certainty}</span><p>{e.description}</p></div></article>)}</div></Page>;
const Fieldwork:React.FC<any>=({options,requests,now,send,openDocument})=><Page><div className="eyebrow">FIELDWORK · ARTHUR VALE</div><h2>Research requests</h2><p className="lede">Arthur can pursue two questions at once. Each report may answer one question while opening another. The delay is intentional: this is an investigation, not a checklist.</p>{requests.length>0&&<div className="field-history">{requests.map((r:Request)=>{const sec=Math.max(0,Math.ceil((r.readyAt-now)/1000));const doc=CASE_001.documents.find(d=>d.id===r.documentId);return <div className="field-row" key={r.id}><div><strong>{r.subject}</strong><small>{r.question}</small></div>{r.complete?<button className="text-button" onClick={()=>doc&&openDocument(doc)}>READ REPORT</button>:<span>{sec}s</span>}</div>})}</div>}<div className="request-grid">{options.filter((o:any)=>!requests.some((r:Request)=>r.id===o.id)).map((o:any)=><button disabled={pendingCount(requests)>=2} className="request-card" key={o.id} onClick={()=>send(o)}><strong>{o.subject}</strong><p>{o.question}</p><span>ASK ARTHUR</span></button>)}</div>{options.length===0&&<p className="empty">No new lead is ready. Re-read the file and interview someone you have overlooked.</p>}</Page>;
const pendingCount=(r:Request[])=>r.filter(x=>!x.complete).length;
const Reports:React.FC<any>=({requests,openDocument})=><Page><div className="eyebrow">FIELD REPORTS</div><h2>Arthur's research</h2><div className="document-list">{requests.map((r:Request)=><button className="document-card read" key={r.id} disabled={!r.complete} onClick={()=>{const d=CASE_001.documents.find(x=>x.id===r.documentId);if(d)openDocument(d)}}><div className="document-type">REPORT</div><div><strong>{r.subject}</strong><small>{r.complete?'Complete':'In progress'}</small></div><span>{r.complete?'OPEN':'WAIT'}</span></button>)}</div>{requests.length===0&&<p className="empty">No reports yet.</p>}</Page>;
const Notebook:React.FC<any>=({notes,setNotes})=><Page><div className="eyebrow">PRIVATE NOTEBOOK</div><h2>Write what bothers you.</h2><p className="lede">Use this for contradictions, hypotheses and questions. It never marks your theory correct.</p><textarea className="notebook" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="The detail I cannot explain yet is..."/></Page>;
const DeductionBoard:React.FC<any>=({evidence,selected,setSelected,theory,setTheory,deductions,create})=><Page><div className="eyebrow">CASE THEORIES</div><h2>Connect facts before accusing anyone</h2><p className="lede">Record at least two competing theories. The final report will ask you to choose between them.</p><div className="deduction-builder"><div className="evidence-mini-grid">{evidence.map((e:Evidence)=><div key={e.id} className={selected.includes(e.id)?'evidence-card selected':'evidence-card'} role="button" tabIndex={0} onClick={()=>setSelected((v:string[])=>v.includes(e.id)?v.filter(id=>id!==e.id):[...v,e.id])}><strong>{e.title}</strong><small>{e.source}</small></div>)}</div><textarea value={theory} onChange={e=>setTheory(e.target.value)} placeholder="Theory: if these facts are connected, then..."/><button className="dark-button" disabled={selected.length<2||theory.trim().length<30} onClick={create}>Record theory</button></div><div className="theory-list">{deductions.length===0&&<p className="empty">No theory recorded.</p>}{deductions.map((d:Deduction)=><article key={d.id}><div className="eyebrow">{d.title} · {d.status.toUpperCase()}</div><p>{d.theory}</p><div className="theory-evidence">{d.evidenceIds.map(id=>evidence.find((e:Evidence)=>e.id===id)?.title).filter(Boolean).map(t=><span key={t}>{t}</span>)}</div></article>)}</div></Page>;
const Choice:React.FC<{label:string;active:boolean;onClick:()=>void;children:React.ReactNode;multi?:boolean}>=({label,active,onClick,children,multi})=><button type="button" className={active?'choice-card selected':'choice-card'} onClick={onClick}><span className="choice-mark">{active?(multi?'✓':'●'):'○'}</span><span><strong>{label}</strong><small>{children}</small></span></button>;
const FinalDeduction:React.FC<any>=({conclusion,setConclusion,selected,evidence,deductions,submit,ready})=>{
 const people=CASE_001.people.filter((p:CasePerson)=>p.id!=='anna');
 const what=[['accident','Anna disappeared after uncovering evidence and a confrontation followed.'],['abduction','Someone deliberately took Anna and tried to make the disappearance look voluntary.'],['staged','Anna deliberately vanished for a reason, leaving a trail for someone to follow.'],['unknown','The evidence is not yet sufficient to choose one explanation.']];
 const when=[['evening','The critical event occurred after the 20:31 transaction and before the late-night door report.'],['rain','The rain window is the strongest external anchor; the apartment clock is unreliable.'],['school','The important sequence began at St. Alden before Anna returned home.'],['uncertain','The exact time cannot yet be proved.']];
 const why=[['coverup','The 1998 record appears to conceal an event connected to people still relevant today.'],['identity','The old record matters because it identifies a person or relationship Anna was investigating.'],['motive','The old record provides a motive for someone to interfere with Anna’s investigation.'],['unresolved','The connection is significant but the motive remains unproven.']];
 const toggleWho=(id:string)=>setConclusion((c:Conclusion)=>({...c,who:c.who.includes(id)?c.who.filter(x=>x!==id):[...c.who,id]}));
 const toggleProof=(id:string)=>setConclusion((c:Conclusion)=>({...c,proof:c.proof.includes(id)?c.proof.filter(x=>x!==id):[...c.proof,id]}));
 const setOne=(k:'what'|'when'|'why',v:string)=>setConclusion((c:Conclusion)=>({...c,[k]:v}));
 return <Page><div className="eyebrow">FINAL DEDUCTION</div><h2>Make the case, not a guess</h2><p className="lede">The final deduction is deliberately structured. You choose the people, the reconstruction and the evidence. No free-text wall, no arbitrary 20-character requirement.</p><section className="final-choice-section"><div className="eyebrow">1 · WHAT HAPPENED?</div>{what.map(([id,text])=><Choice key={id} label={id==='accident'?'Confrontation / accident':id==='abduction'?'Deliberate abduction':id==='staged'?'Deliberate disappearance':'Not enough evidence'} active={conclusion.what===id} onClick={()=>setOne('what',id)}>{text}</Choice>)}</section><section className="final-choice-section"><div className="eyebrow">2 · WHO WAS INVOLVED?</div><p className="choice-hint">Select everyone you believe was directly involved. More than one answer may be correct.</p>{people.map((p:CasePerson)=><Choice key={p.id} label={p.name} active={conclusion.who.includes(p.id)} onClick={()=>toggleWho(p.id)} multi>{p.role}</Choice>)}</section><section className="final-choice-section"><div className="eyebrow">3 · WHEN IS THE CRITICAL WINDOW?</div>{when.map(([id,text])=><Choice key={id} label={id==='evening'?'After the card transaction':id==='rain'?'Around the rain window':id==='school'?'Before Anna returned home':'Exact time unresolved'} active={conclusion.when===id} onClick={()=>setOne('when',id)}>{text}</Choice>)}</section><section className="final-choice-section"><div className="eyebrow">4 · WHY DOES 1998 MATTER?</div>{why.map(([id,text])=><Choice key={id} label={id==='coverup'?'A buried school cover-up':id==='identity'?'A hidden identity / relationship':id==='motive'?'A motive for the present case':'Connection known, motive unresolved'} active={conclusion.why===id} onClick={()=>setOne('why',id)}>{text}</Choice>)}</section><section className="final-choice-section"><div className="eyebrow">5 · WHICH PROOF SUPPORTS YOUR CONCLUSION?</div>{evidence.map((e:Evidence)=><Choice key={e.id} label={e.title} active={conclusion.proof.includes(e.id)} onClick={()=>toggleProof(e.id)} multi>{e.description}</Choice>)}</section><div className="final-evidence"><strong>{selected.length} evidence cards cited on board · {deductions.length} theories recorded</strong></div><button className="dark-button" disabled={!ready} onClick={submit}>{ready?'Submit final report':'Choose what happened, at least one person, a time window, why 1998 matters and 3+ proof items'}</button></Page>;
};
const Submitted:React.FC<{onContinue:()=>void}>=({onContinue})=><div className="ending"><div className="eyebrow">CASE-001 · REPORT SUBMITTED</div><h1>The file leaves Blackwood.</h1><p>Your reconstruction has been sent to North District Police. The answer is not revealed immediately.</p><p>Seven days later, a sealed addendum arrives.</p><button className="dark-button" onClick={onContinue}>Open the addendum</button></div>;
const Newspaper:React.FC=()=> <div className="ending newspaper"><div className="eyebrow">CASE-001 · SEALED ADDENDUM</div><article><div className="paper-masthead">NORTH DISTRICT INVESTIGATION BUREAU</div><h1>THE EMPTY ROOM — CASE REOPENED</h1><p className="paper-subtitle">Investigators found the original 1998 pages in a private storage unit connected to the present investigation.</p><p>Police confirmed that Anna Bell did not simply leave town. Her disappearance was connected to a chain of concealed records, false assumptions and a meeting that had been deliberately kept out of the original file.</p><p>The investigation remains open. Blackwood's report became the starting point, not the ending.</p></article><div className="next-file"><div className="eyebrow">NEXT FILE</div><h2>CASE-002</h2><p>Another client is waiting. This time, the first witness is lying.</p><span>INCOMING FILE · INDEPENDENT CASE</span></div></div>;
const Modal:React.FC<any>=({title,close,children})=><div className="modal-backdrop" onMouseDown={close}><article className="modal-card" onMouseDown={(e)=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><div className="eyebrow">BLACKWOOD FILE</div><h3>{title}</h3>{children}</article></div>;
const Page:React.FC<{children:React.ReactNode}>=({children})=><section className="page">{children}</section>;
const Stat:React.FC<{label:string;value:number}>=({label,value})=><div className="stat"><span>{label}</span><strong>{value}</strong></div>;
